### ISSUE TITLE
Plugin reload causes crash

### ISSUE THREAD

**Issue by lucasw** [lucasw/dynamic_reconfigure_tools#17]
```
roslaunch rqt_dr_single demo_dr_single.launch
rqt
```
then add an rqt dr single plugin, select one of the example servers, press the reload button in the top (not the dropdown reload button within the widget).

```
Traceback (most recent call last):
  File "/home/lucasw/catkin_ws/src/dynamic_reconfigure_tools/rqt_dr_single/src/rqt_dr_single/dr_single.py", line 322, in update_config
    self.val_label[param_name].setText(str(config[param_name]))
RuntimeError: wrapped C/C++ object of type QLineEdit has been deleted

```

**Comment by lucasw** [comment]
The reload is actually going through shutdown and `__init__` again.

**Comment by calebschoepp** [comment]
@lucasw  I seem to be having a similar issue. Did you add something special to either `shutdown_plugin` or `__init__` to resolve the issue?

**Comment by lucasw** [comment]
From my last commit it looks like this wasn't resolved or was re-introduced- though a commit like 88fa082d7b8693b34f6ca7ef8f075c0aa1c60add may work better than the more recent ones.  I haven't been using ros1 and dynamic reconfigure recently (having moved on to ros2) but could take a look at fixing this eventually.

**Comment by calebschoepp** [comment]
I should clarify, my issue isn't actually with dynamic reconfigure. I am trying to debug a custom python plugin for RQT and I am getting a similar error where the python wrapper tries to access a c++ object that has already been deleted. I think it has something to do with the `shutdown_plugin` function and was just trying to see if there is anything specific you did in the function. Thanks.

**Comment by lucasw** [comment]
What I did in 28c8549 was remove all the widgets in shutdown_plugin so that a callback (in a different thread- a ros thread as opposed to a qt one?) wouldn't be able to access a deleted widget, though maybe it is possible the widget could be deleted mid-callback.  Almost all the widgets here are in dicts which the shutdown clears so if a callback can't find a key in one it won't try to use it, as opposed to `self.connected_checkbox = self._widget.findChild(QCheckBox, 'connected_checkbox')` (though a shutdown could set connected_checkbox to None, and every method that uses it needs to check for None, or something like that).
